//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientInfo
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string BrandName { get; set; }
        public string WebsiteURL { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Zip { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
